// flow-typed signature: 063228aeabed7b0191f48fb49e31b906
// flow-typed version: <<STUB>>/@geostarters/eslint-config_v0.0.6/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@geostarters/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@geostarters/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@geostarters/eslint-config/index' {
  declare module.exports: $Exports<'@geostarters/eslint-config'>;
}
declare module '@geostarters/eslint-config/index.js' {
  declare module.exports: $Exports<'@geostarters/eslint-config'>;
}
