// flow-typed signature: c68b638761c6283b3c76acc0faea8653
// flow-typed version: <<STUB>>/@types/tap_v^15.0.7/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/tap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/tap' {
  declare module.exports: any;
}
