// flow-typed signature: 7dae56f049de82c3e05f17125cf159b6
// flow-typed version: <<STUB>>/derequire_v^2.0.6/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'derequire'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'derequire' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'derequire/bin/cmd' {
  declare module.exports: any;
}

declare module 'derequire/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'derequire/bin/cmd.js' {
  declare module.exports: $Exports<'derequire/bin/cmd'>;
}
declare module 'derequire/index' {
  declare module.exports: $Exports<'derequire'>;
}
declare module 'derequire/index.js' {
  declare module.exports: $Exports<'derequire'>;
}
declare module 'derequire/plugin.js' {
  declare module.exports: $Exports<'derequire/plugin'>;
}
