// flow-typed signature: dfd286d95e8f34df9d6fbae2ec61cd44
// flow-typed version: <<STUB>>/execcommand-copy_v^1.1.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'execcommand-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'execcommand-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'execcommand-copy/index' {
  declare module.exports: $Exports<'execcommand-copy'>;
}
declare module 'execcommand-copy/index.js' {
  declare module.exports: $Exports<'execcommand-copy'>;
}
