// flow-typed signature: 9c03f45202a7a26a80cd3d4ed745aa66
// flow-typed version: <<STUB>>/minifyify_v^7.3.5/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minifyify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minifyify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minifyify/lib' {
  declare module.exports: any;
}

declare module 'minifyify/lib/minifier' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/backbone app/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/backbone app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/backbone app/view' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/brfs app/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/brfs app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with exclude filter/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with exclude filter/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with exclude filter/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with exclude filter/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with filters/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with filters/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with filters/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with filters/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with include filter/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with include filter/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with include filter/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file with include filter/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/complex file/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/custom base path/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/custom base path/dirA/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/custom base path/dirB/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/custom base path/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/default base path/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/default base path/dirA/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/default base path/dirB/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/default base path/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/native libs/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/native libs/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/native libs/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/simple file/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/simple file/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/transformed app/bundle.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/build/apps/transformed app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/bundles' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/backbone app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/backbone app/view' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/brfs app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with exclude filter/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with exclude filter/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with exclude filter/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with filters/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with filters/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with filters/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with include filter/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with include filter/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file with include filter/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/complex file/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/custom base path/dirA/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/custom base path/dirB/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/custom base path/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/default base path/dirA/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/default base path/dirB/subsubmodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/default base path/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/Backbone' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/Backbone.min' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/HandlebarsRuntime' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/Jquery' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/Lodash' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/libraries/Underscore' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/native libs/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/native libs/submodule' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/simple file/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/fixtures/transformed app/entry' {
  declare module.exports: any;
}

declare module 'minifyify/test/plugin-api' {
  declare module.exports: any;
}

declare module 'minifyify/test/user-errors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minifyify/lib/index' {
  declare module.exports: $Exports<'minifyify/lib'>;
}
declare module 'minifyify/lib/index.js' {
  declare module.exports: $Exports<'minifyify/lib'>;
}
declare module 'minifyify/lib/minifier.js' {
  declare module.exports: $Exports<'minifyify/lib/minifier'>;
}
declare module 'minifyify/test/build/apps/backbone app/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/backbone app/bundle.min'>;
}
declare module 'minifyify/test/build/apps/backbone app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/backbone app/entry'>;
}
declare module 'minifyify/test/build/apps/backbone app/view.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/backbone app/view'>;
}
declare module 'minifyify/test/build/apps/brfs app/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/brfs app/bundle.min'>;
}
declare module 'minifyify/test/build/apps/brfs app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/brfs app/entry'>;
}
declare module 'minifyify/test/build/apps/complex file with exclude filter/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with exclude filter/bundle.min'>;
}
declare module 'minifyify/test/build/apps/complex file with exclude filter/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with exclude filter/entry'>;
}
declare module 'minifyify/test/build/apps/complex file with exclude filter/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with exclude filter/submodule'>;
}
declare module 'minifyify/test/build/apps/complex file with exclude filter/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with exclude filter/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/complex file with filters/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with filters/bundle.min'>;
}
declare module 'minifyify/test/build/apps/complex file with filters/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with filters/entry'>;
}
declare module 'minifyify/test/build/apps/complex file with filters/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with filters/submodule'>;
}
declare module 'minifyify/test/build/apps/complex file with filters/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with filters/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/complex file with include filter/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with include filter/bundle.min'>;
}
declare module 'minifyify/test/build/apps/complex file with include filter/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with include filter/entry'>;
}
declare module 'minifyify/test/build/apps/complex file with include filter/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with include filter/submodule'>;
}
declare module 'minifyify/test/build/apps/complex file with include filter/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file with include filter/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/complex file/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file/bundle.min'>;
}
declare module 'minifyify/test/build/apps/complex file/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file/entry'>;
}
declare module 'minifyify/test/build/apps/complex file/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file/submodule'>;
}
declare module 'minifyify/test/build/apps/complex file/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/complex file/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/custom base path/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/custom base path/bundle.min'>;
}
declare module 'minifyify/test/build/apps/custom base path/dirA/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/custom base path/dirA/submodule'>;
}
declare module 'minifyify/test/build/apps/custom base path/dirB/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/custom base path/dirB/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/custom base path/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/custom base path/entry'>;
}
declare module 'minifyify/test/build/apps/default base path/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/default base path/bundle.min'>;
}
declare module 'minifyify/test/build/apps/default base path/dirA/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/default base path/dirA/submodule'>;
}
declare module 'minifyify/test/build/apps/default base path/dirB/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/default base path/dirB/subsubmodule'>;
}
declare module 'minifyify/test/build/apps/default base path/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/default base path/entry'>;
}
declare module 'minifyify/test/build/apps/native libs/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/native libs/bundle.min'>;
}
declare module 'minifyify/test/build/apps/native libs/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/native libs/entry'>;
}
declare module 'minifyify/test/build/apps/native libs/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/native libs/submodule'>;
}
declare module 'minifyify/test/build/apps/simple file/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/simple file/bundle.min'>;
}
declare module 'minifyify/test/build/apps/simple file/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/simple file/entry'>;
}
declare module 'minifyify/test/build/apps/transformed app/bundle.min.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/transformed app/bundle.min'>;
}
declare module 'minifyify/test/build/apps/transformed app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/build/apps/transformed app/entry'>;
}
declare module 'minifyify/test/bundles.js' {
  declare module.exports: $Exports<'minifyify/test/bundles'>;
}
declare module 'minifyify/test/fixtures/backbone app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/backbone app/entry'>;
}
declare module 'minifyify/test/fixtures/backbone app/view.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/backbone app/view'>;
}
declare module 'minifyify/test/fixtures/brfs app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/brfs app/entry'>;
}
declare module 'minifyify/test/fixtures/complex file with exclude filter/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with exclude filter/entry'>;
}
declare module 'minifyify/test/fixtures/complex file with exclude filter/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with exclude filter/submodule'>;
}
declare module 'minifyify/test/fixtures/complex file with exclude filter/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with exclude filter/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/complex file with filters/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with filters/entry'>;
}
declare module 'minifyify/test/fixtures/complex file with filters/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with filters/submodule'>;
}
declare module 'minifyify/test/fixtures/complex file with filters/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with filters/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/complex file with include filter/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with include filter/entry'>;
}
declare module 'minifyify/test/fixtures/complex file with include filter/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with include filter/submodule'>;
}
declare module 'minifyify/test/fixtures/complex file with include filter/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file with include filter/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/complex file/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file/entry'>;
}
declare module 'minifyify/test/fixtures/complex file/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file/submodule'>;
}
declare module 'minifyify/test/fixtures/complex file/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/complex file/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/custom base path/dirA/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/custom base path/dirA/submodule'>;
}
declare module 'minifyify/test/fixtures/custom base path/dirB/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/custom base path/dirB/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/custom base path/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/custom base path/entry'>;
}
declare module 'minifyify/test/fixtures/default base path/dirA/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/default base path/dirA/submodule'>;
}
declare module 'minifyify/test/fixtures/default base path/dirB/subsubmodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/default base path/dirB/subsubmodule'>;
}
declare module 'minifyify/test/fixtures/default base path/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/default base path/entry'>;
}
declare module 'minifyify/test/fixtures/index' {
  declare module.exports: $Exports<'minifyify/test/fixtures'>;
}
declare module 'minifyify/test/fixtures/index.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures'>;
}
declare module 'minifyify/test/fixtures/libraries/Backbone.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/Backbone'>;
}
declare module 'minifyify/test/fixtures/libraries/Backbone.min.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/Backbone.min'>;
}
declare module 'minifyify/test/fixtures/libraries/HandlebarsRuntime.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/HandlebarsRuntime'>;
}
declare module 'minifyify/test/fixtures/libraries/Jquery.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/Jquery'>;
}
declare module 'minifyify/test/fixtures/libraries/Lodash.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/Lodash'>;
}
declare module 'minifyify/test/fixtures/libraries/Underscore.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/libraries/Underscore'>;
}
declare module 'minifyify/test/fixtures/native libs/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/native libs/entry'>;
}
declare module 'minifyify/test/fixtures/native libs/submodule.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/native libs/submodule'>;
}
declare module 'minifyify/test/fixtures/simple file/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/simple file/entry'>;
}
declare module 'minifyify/test/fixtures/transformed app/entry.js' {
  declare module.exports: $Exports<'minifyify/test/fixtures/transformed app/entry'>;
}
declare module 'minifyify/test/plugin-api.js' {
  declare module.exports: $Exports<'minifyify/test/plugin-api'>;
}
declare module 'minifyify/test/user-errors.js' {
  declare module.exports: $Exports<'minifyify/test/user-errors'>;
}
