// flow-typed signature: 67f01de6c271605d9ee6f847d799b034
// flow-typed version: <<STUB>>/package-json-versionify_v^1.0.4/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package-json-versionify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'package-json-versionify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'package-json-versionify/index' {
  declare module.exports: $Exports<'package-json-versionify'>;
}
declare module 'package-json-versionify/index.js' {
  declare module.exports: $Exports<'package-json-versionify'>;
}
